server:
  port:8080

spring:
  application:
    name: customer

  datasource:
    url: jdbc:mysql://localhost:3306/demoservice
    username:
    password:
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
      hibernate:
        ddl-auto: update
      show-sql: true